name: Mirror and run GitLab CI

on: [push, pull_request_target]

env:
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
  # Repo-URL without https:// at beginning!
  GITLAB_REPO_URL: "codebase.helmholtz.cloud/j.fritz/github2gitlab_dummy.git"
  FORCE_PUSH: "true"
  GITLAB_HOSTNAME: "codebase.helmholtz.cloud"
  GITLAB_PROJECT_ID: "6234"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # svanboxel:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Mirror + trigger CI
  #     uses: SvanBoxel/gitlab-mirror-and-ci-action@master
  #     with:
  #       args: "https://gitlab.hzdr.de/j.fritz/github2gitlab_dummy.git"
  #     env:
  #       FORCE_PUSH: "true"
  #       GITLAB_HOSTNAME: "gitlab.hzdr.de"
  #       GITLAB_USERNAME: "j.fritz"
  #       GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
  #       GITLAB_PROJECT_ID: "6234"
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubc_github2gitlab:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: pull github2gitlab
        uses: actions/checkout@v3
        with:
          repository: jakob-fritz/gitlab-mirror-and-ci-action
          ref: non_docker
          path: github2gitlab_action
      - name: Mirror
        run: |
          chmod +x ./github2gitlab_action/mirror.sh
          ./github2gitlab_action/mirror.sh
      - name: Get state of Gitlab-CI
        run: |
          chmod +x ./github2gitlab_action/get_ci_state.sh
          ./github2gitlab_action/get_ci_state.sh
